Update README.md
ms1-learner/python-01-en pull request #4
Opened 2024-01-24 11:51 UTC by woven-baker

2024-02-01 06:16 UTC, dancer-yuma requested changes
@woven-baker 
Most of the things look good to me, there is just one typo.

2024-02-01 06:16 UTC, dancer-yuma commented on 02_more_strings_and_control_flow/02_challenge/README.md
> +In the `factorial.py` file, write a program that takes a non-negative integer from the user and computes the factorial of this given number. The factorial of a number `n`, denoted by `n!`, is the pro
Typo

```suggestion
In the `factorial.py` file, write a program that takes a non-negative integer from the user and computes the factorial of this given number. The factorial of a number `n`, denoted by `n!`, is the product of all positive integers less than or equal to n. The factorial function is defined as `n! = n x (n - 1) x (n - 2) x ... x 3 x 2 x 1`. Please note that the factorial of `0` is actually `1`. Make sure your program is able to handle this case.
```

2024-02-14 09:33 UTC, woven-baker commented
@dancer-yuma I fixed the conflicts. Madi changed a lot of stuff in main to it got a bit complicated. Should be all fixed now.

2024-02-15 00:31 UTC, dancer-yuma approved these changes
@woven-baker 
Looks good to me!

2024-02-15 01:35 UTC, merged