Update Challenge 01/01/1
ms1-learner/python-01-en pull request #5
Opened 2024-02-07 07:53 UTC by abolinsky

2024-02-07 13:40 UTC, lordmadi requested changes

2024-02-07 13:40 UTC, lordmadi commented on 01_introduction_to_software_development_in_python/01_challenge/README.md
> +- Manually convert each string to its correct number representation. Save each converted number to its own variable.
"Manually Convert" feels like the student has the option to just create a new variable for the converted numbers. 

This is an early challenge in the course and it's important they see the `float` and `int` in the instructions. I think we should leave it as is.

2024-02-08 01:49 UTC, abolinsky commented on 01_introduction_to_software_development_in_python/01_challenge/README.md
> +- Manually convert each string to its correct number representation. Save each converted number to its own variable.
@lordmadi I've just revised. The previous wording was tripping up the QA learners because of how it focused on the strings with and without dots, which made them think they needed to use conditionals and other language features to look for dots in the strings.

2024-02-08 02:29 UTC, lordmadi commented on 01_introduction_to_software_development_in_python/01_challenge/README.md
> +- Manually convert each string to its correct number representation. Save each converted number to its own variable.
@lordmadi Much clearer now! Thank you for the update.

2024-02-08 02:30 UTC, lordmadi approved these changes

2024-02-08 02:48 UTC, merged